default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: classifieds_reviewer_development

test:
  <<: *default
  database: classifieds_reviewer_test

production:
  <<: *default
  database: classifieds_reviewer_production